### ISSUE TITLE
Recording to sound file doesn't work if the sound file name doesn't end in .wav | .aiff | .aif

### ISSUE THREAD

**Issue by jackkilgore** [EmissionControl2/EmissionControl2#100]
The default behavior should implicitly append .wav to the "Sound Output File Name", if no extension is specified.

**Comment by leescan** [comment]
great call, just found this out the hard way. I do love this creative tool

**Comment by rodneydup** [comment]
Fixed in recent commit. The fix will be included in the next EC2 release.
