### ISSUE TITLE
I cannot run Emissioncontrol

### ISSUE THREAD

**Issue by spectromas** [EmissionControl2/EmissionControl2#103]
I'm using arch + pipewire and I'm having problems with emissioncontrol. It won't start unless I start qjackctl with 1024 frames and even then I cannot get any sound out. I can see it in the qjackctl graph and it is connected but clicking on Engine Start does nothing. If I go to the Audio Output and press Stop, EM2 crashes when I try to start again.

When I run from a terminal I get this: 

```
RtApi::openStream: a stream is already open!
RtApiJack::startStream(): error connecting output ports!

```

I'm not sure why it can't connect, everything else can.

**Comment by rodneydup** [comment]
same as #106... working on this.
