### ISSUE TITLE
Midi Learn LFO 6 Modulation Amount Targets Morph Time Parameter

### ISSUE THREAD

**Issue by CFlickster** [EmissionControl2/EmissionControl2#105]
Steps to repro (v1.1):
open ec2
right click the slider for LFO 6 in the modulation section
select MIDI Learn
--->BUG - Morph Time is highlighted green and receives the MIDI map you're attempting to make for LFO 6

**Comment by rodneydup** [comment]
I'm not able to reproduce this. I right click on lfo 6, select midi learn, and the lfo 6 slider turns green and my slider moves it.

Sorry for the delay in responding to this, but are you still getting this issue?
