### ISSUE TITLE
Segmentation fault on Ubuntu (20.04)

### ISSUE THREAD

**Issue by Blindekinder** [EmissionControl2/EmissionControl2#106]
EC2 crashes sometimes on launch, sometimes on engine start , sometimes on engine stop.

Used with Jack 2 (1.9.19), started, on Kubuntu 20.04

```
~$ emissioncontrol2
[!] [createDir] /home/raphael/.config/EmissionControl2/config already exists
[!] [createDir] /home/raphael/.config/EmissionControl2/presets already exists
[!] [createDir] /home/raphael/.config/EmissionControl2/midi_presets already exists
[!] [createDir] /home/raphael/.config/EmissionControl2/sample_presets already exists
Opened port to Midi Through:Midi Through Port-0 14:0
I/O Device:  [ 0] system,  2 out, 48000 Hz
Chans In:    0 (0D + 0V)
Chans Out:   2 (2D + 0V)
Frames/Buf:  1024
Frame Rate:  48000
Parameter OSC Handshake server running on 0.0.0.0:16987
WARNING: Device opened with buffer size: 256
RtApi::openStream: a stream is already open!

Erreur de segmentation (core dumped)
```

**Comment by spectromas** [comment]
I'm getting exactly the same thing as well. Seems like it expects 1024 frames for some reason.

**Comment by rodneydup** [comment]
We are soon releasing version 1.2 of the app with some new features and I am looking into this bug.

Actually I am having this bug sometimes myself on Linux with Pipewire. It's hard to solve. It looks like RtAudio (the underlying audio library in EC2) requires us to hardcode the buffer size. so when that doesn't match the system buffer size, it just crashes. I need to somehow get RtAudio to match the buffer size of the system, but it doesn't seem like it can do that.... unless I'm missing something.

Will update soon. (and sorry for how long it took to respond to this issue)

**Comment by rodneydup** [comment]
Ok I can't make EC2 automatically adapt to the output device's buffer size, but I have now made it manually adjustable! This is in the latest commit. It will be in the next release as well, which is coming soon.

There are still some issues with pipewire unfortunately. I've tried many things, but it looks like it's a limitation of the audio backends EC2 is built on. The best solution I've found for pipewire users is to compile the app without jack support (using PulseAudio instead). I hate to split the installers in two, but for the next big release, I guess I will include an installer for pulseaudio/pipewire in addition to the one that supports JACK.

**Comment by mantaraya36** [comment]
You could try updating RtAudio within allolib to see if it has been fixed
in a newer version. If it is, I can update the RtAudio submodule in allolib.

**Comment by rodneydup** [comment]
Thanks @mantaraya36. It doesn't seem like rtaudio has fixed it.

@Blindekinder and @spectromas we have just released v1.2 which includes the ability to manually set your buffer size. Also, if you're using Pipewire in your audio stack, I recommend using the NOJACK version included in the zip file because it sidesteps a problem where pipewire sets varying buffer sizes for different JACK ports.

Hopefully this new version will work better for you!

**Comment by Blindekinder** [comment]
I tried both debian-precompiled and build from git but I get errors...

**Comment by rodneydup** [comment]
Is it the same kind of error as before? Does it crash before it opens? Or when you start the audio engine? Have you tried setting the buffer size in EC2 audio settings to match your system?
