### ISSUE TITLE
OSC : Preset messages change Current Preset to none

### ISSUE THREAD

**Issue by DavidPiazza** [EmissionControl2/EmissionControl2#114]
When sending a /preset [some_integer] message to EC2, the Current Preset parameter switches to "none", no matter the value being sent.

**Comment by DavidPiazza** [comment]
macOS 12.6
Intel Core i5
EmissionControl2 version 1.2
sending OSC via Max 8.33

**Comment by rodneydup** [comment]
Thanks for pointing this out. Luckily it seemed to be just a visual glitch, and the presets were still changing as they should behind the scenes. Still annoying though!

This is fixed in the latest commit and will be included in the next release coming shortly.
