### ISSUE TITLE
OSC control parameters not recognized correctly

### ISSUE THREAD

**Issue by heinzhar** [EmissionControl2/EmissionControl2#115]
Hi together

I'm trying to automate a piece in EmissionControl2. Using bash, python-osc and CHON on Linux for parameter and timing adjustments.

During the tests, I recognized that some parameters sent via OSC are not recognized correctly by EC2 or not recognized at all.

The issue is reproducible in [python-osc.](https://pypi.org/project/python-osc/)

Each control parameter has been tested in EC2 default state without starting the engine. A cross check to rule out a OSC client issue has been done.

The following EmissionsControl2 control settings are affected:

Granulation Controls
- Grain Rate
- Grain Duration

Modulation Controls
- all LFO’s

LFO Controls
- all LFO’s
- LFO6 doesn’t recognize OSC parameter at all

**All other EmissionsControl2 control settings are unaffected by the issue.**

Reproduction steps on linux (for example...):

```
sudo apt install python3
sudo apt install pip
pip install python-osc
python3
from pythonosc.udp_client import SimpleUDPClient
ip = "127.0.0.1"
port = 16447
client = SimpleUDPClient(ip, port)
client.send_message("/GrainRate", 5.000)
```

The findings so far:

Grain Rate (at default setting):
When 5.000 is sent via python-osc >>>  EC2 slider is set to 4.956
When then 4.000 is sent >>> EC2 slider is set to 3.965
When then 1.000 is sent >>> EC2 slider is set to 0.992
When then 21.888 is sent >>> EC2 slider is set to 21.692

Modulation Controls
When 0.666 is sent via python-osc >>> EC2 slider is set correctly to 0.666
When 0.666 is sent a 2nd time >>> EC2 slider is set back to 0
When 0.666 is sent a 3rd time >>> EC2 slider is set to 0.666
When then 0.999 is sent  >>> EC2 slider is set to 0.333

This behavior is reproducible on each modulation control slider 

LFO Controls (all sliders set to default):
When 20.000 is sent via python-osc >>> EC2 slider is set to 18.383
When 20.000 is sent a 2nd time >>> EC2 slider is set to 1.574
When 20.000 is sent a 3rd time >>> EC2 slider stays at 1.574
When then 1.000 is sent >>> EC2 slider is set to 0.010
LFO6 does not recognize OSC data and stays at the default setting

Hope this helps.

Many thanks!

**Comment by rodneydup** [comment]
Thank you for finding this! It was the result of two bugs in the code: a rounding error and also (for the mod and lfo controls) the wrong variable being used.

It's fixed in the latest commit, and will be included in the next release which will come out shortly.

**Comment by heinzhar** [comment]
Thank you for taking the time to fix the issue. I look forward to trying out the next release.
