### ISSUE TITLE
Recording unused output channels

### ISSUE THREAD

**Issue by agdfrnd** [EmissionControl2/EmissionControl2#62]
I'm on macOS 10.15.6. My audio interface is a Komplete Audio 6, with 6 potential output channels. When I record a file from EmissionControl, it creates a 6-channel audio file -- the latter four channels are silent. I would expect this to generalize to other audio interfaces with more than two outputs. I don't know whether you plan to add support for configurations beyond stereo later on, but it would be convenient if the file-recording function only recorded the channels that EmissionControl actually uses.

**Comment by jackkilgore** [comment]
Fixed on commit: 3b9b32cd7bd8b0f991dbd9ecb8b6835da0223221
Was a one-liner so I feel it didn't need its own branch :P 
Thanks for pointing this out!
