### ISSUE TITLE
Assertion failure within ImGui

### ISSUE THREAD

**Issue by dnlopez** [EmissionControl2/EmissionControl2#64]
Hi - the program works for me normally but on compiling it in debug mode I found it exiting immediately on startup with an assertion failure:

```/home/daniel/archbuilds/sound/EmissionControl2/ecSource/external/allolib/external/imgui/imgui.cpp:6872: void ImGui::ErrorCheckBeginEndCompareStacksSize(ImGuiWindow*, bool): Assertion `*p >= n && "PushFont/PopFont Mismatch!"' failed.```

which appeared to be caused by this at line 909 of ecInterface.cpp:
```
      ImGui::PopFont();
    }
    NextWindowYPosition += graphHeight / 3;
```
where the 'PopFont' really ought to be below the closing brace, because if you look at the matching opening brace above it:
```
    ImGui::PushFont(bodyFont);
    if (granulator.getNumberOfAudioFiles() != 0) {
```
the 'PushFont' is outside it so there'll be an imbalance if the body of the 'if' statement doesn't get executed. When I moved the 'PopFont' down below the brace this particular issue stopped happening here.

**Comment by rodneydup** [comment]
Great catch. That happened with a last minute addition of that if statement before we released.

I decided to rather put the pushfont inside the 'if' statement. Fixed with https://github.com/EmissionControl2/EmissionControl2/commit/7a8548c2c3b744b25e49ae2a2023c584b85061e6
