### ISSUE TITLE
EC2 does not work on ALSA [LINUX]

### ISSUE THREAD

**Issue by rodneydup** [EmissionControl2/EmissionControl2#66]
EC2 will consistently crash at startup if neither JACK nor Pulseaudio are running (i.e. if it tries to connect to ALSA directly).

Tested on Arch and Debian.

Checked RTAudio flags and it seems to be compiling with support for all three (ALSA, Pulseaudio, JACK).

Expected behavior: if JACK is running, connect to JACK. Else fall back to PulseAudio. If neither are running, fall back to ALSA.

**Comment by secretrow** [comment]
I used EC2 with JACK successfully for months, but today the application either closes when I start the engine, or crashes at startup. 

Full JACK error message here: 

https://pastebin.com/RNTD48Tz

When I try to connect cables to EC2 in QjackCtl, I get: 

`ERROR: Cannot connect ports owned by inactive clients: "EmissionControl2" is not active
`

Not sure what changed, as JACK works fine with other software.. any advice would be appreciated !

**Comment by rodneydup** [comment]
When the audio engine of EC2 is off, you can't make connections. This is a quirk that arises because when engine is off, we fully shut off the audio engine. As in, as far as your system can tell, there's no audio app there when audio engine is off. This is so that the user can configure audio settings and restart the engine with the new settings. The case where EC2 still appears for jack but you can't make connections is odd but not a major issue in most cases, because the app should auto-connect when the engine is turned on, and the user can manually change connections when the engine is on.

The other part about crashes at startup and crashes when you start the engine concern me though. Are you still using version 1.01 from October? Have you tried the new version we published yesterday? Either way, if you could try on both and let me know if there's a difference, that would be helpful.

It would also be helpful if you could run `emissioncontrol2` from the terminal, get the output when it crashes, and paste it here.

**Comment by rodneydup** [comment]
Also, I do know that EC2 crashes if you start the audio engine and your system is set to a different buffer size than the buffer size set in EC2 (check in Audio->Audio output). This is obviously not ideal, but kind of to be expected. It would be nice for EC2 to just auto-detect the audio card's buffer size and default to that, but we haven't found a way to do that.

Just mentioning in case that's the issue here.

**Comment by secretrow** [comment]
Thanks for your quick reply! 

I didn't realize there was a new version, the new features look great! Should I uninstall v1.01, or can they co-exist? 

Here's my v1.01 terminal output. 

```
$ emissioncontrol2
[!] [createDir] /home/mickey/.config/EmissionControl2/config already exists
[!] [createDir] /home/mickey/.config/EmissionControl2/presets already exists
[!] [createDir] /home/mickey/.config/EmissionControl2/midi_presets already exists
Opened port to Midi Through:Midi Through Port-0 14:0
I/O Device:  [ 0] system,  2 in,  2 out, 48000 Hz
Chans In:    0 (0D + 0V)
Chans Out:   2 (2D + 0V)
Frames/Buf:  1024
Frame Rate:  48000
Handshake server running on 0.0.0.0:16987
WARNING: Device opened with buffer size: 2048
RtApi::openStream: a stream is already open!

Segmentation fault (core dumped)

```

Your tip about buffer sizes needing to match predicted my error. Once they match it runs fine, so thank you!  

I do think It would be nice to be able to change buffer size in EC2... for those who prefer larger buffers to prevent Xruns and don't really care about latency. 

But thanks for your help and for making such awesome software!

**Comment by shiphouse** [comment]
Hi,

You can change the value of the following variable in the const.h file and rebuild the whole thing:

const int BLOCK_SIZE = 1024;

(The 1024 value is very high for me and affects to the jack audio system latency. Currently I am using a small ESI 24 XL sound device).

I have tested with good results with 128 value as block size on Em2 using the same frames/period entry on Jack. Using other frame size values some sound artifacts and noises are occurring.

Also, I have put a new entry into the config.json file to try to pass the block size value at init. (BLOCK_SIZE=128)

I could send you the code if you think that would be useful.

Thank you.

{"BLOCK_SIZE":128, ...}

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodul

es)
	modified:   ../external/al_ext (modified content)
	modified:   ../include/ecInterface.h
	modified:   ecInterface.cpp
