### ISSUE TITLE
[Feature request] Add the option to input Midi CC# manually, not just via midi learn

### ISSUE THREAD

**Issue by biomassa** [EmissionControl2/EmissionControl2#70]
It would be amazing to have an option to set midi CC numbers for sliders without doing midi learn for each of them. Currently it's a bit of a mess when modulating a lot of parameters. Thanks!

**Comment by jackkilgore** [comment]
Agreed, I would like to implement this sometime soon (it will make doing OSC easier too), for now, you can save midi presets so you only have to go through a lot of the pain once (HAH). I shall put this on my todo list!

**Comment by biomassa** [comment]
Thanks! That would be convenient (but there is of course no urgency, it's pretty minor!)
