### ISSUE TITLE
int parameter modulation snapping

### ISSUE THREAD

**Issue by rodneydup** [EmissionControl2/EmissionControl2#74]
Sound File is one of the few "int" parameters so modulating it is a bit strange. The LFO or midi controller needs to reach a certain threshold before the parameter snaps to the next sound file. One bug with this I've found is this:

1. Have 2 soundfiles loaded in.
2. Set modulator 8 to maximum.
3. Set the LFO connected to modulator 8 to UNI+ on Sine.

Expected behavior is that the second sound file should become active at some point, but it doesn't. The reason is clearly because the threshold for snapping to the second sound file is the maximum value of the parameter slider, and the sine LFO never actually reaches that value or if it does, it's only for a few milliseconds.

I feel that we could make this more intuitive. I think we should set the threshold for the snap to be 0.5 for the case of 2 sound files, 0.33 and 0.66 for the case of 3 sound files, 0.25, 0.5, 0.75 for the case of 4 sound files, etc. So essentially the snap points are 1/n apart. To achieve this with not too much overhead, I think we can simply perform this operation on the mod for int parameters: 

snappedModVal = floor(modVal * numberOfSteps)

This would be a better behavior for the other int parameter (Streams) as well, I think.

**Comment by Saccobakunin** [comment]
This may be related to the bug. I have loaded a few sound files and I want to use an LFO to rapidly switch between them as the files are scanned. However, when I apply the LFO to the sound file selector the scan sticks in one place.

-Scott Perry

**Comment by jackkilgore** [comment]
Fixed this issue. I thought this was a design flaw but it was just a straight bug. The thresholding you proposed @rodneydup was there, I was just accidentally destroying it with a liberal use of integer type casting LOL.

Before: Flooring (int casting to be exact) all integer parameter modulators.
After: Floor if decimal portion is less than 0.5, ceiling ow. 

This should work as expected in your two sound file example.

#90
