### ISSUE TITLE
Samples not saved after exit program?

### ISSUE THREAD

**Issue by Springreverb1** [EmissionControl2/EmissionControl2#77]
Samples are not saved upon relaunching the program?

**Comment by jackkilgore** [comment]
That is the expected behavior at the moment; however, I have thought about adding a feature where you have the option to save the current files loaded into the "initial sample directory", I will mark this as a feature request and put it on the list, thanks!

**Comment by jackkilgore** [comment]
Fixed in some commit long ago. In the future I will be better at documenting these changes.
