### ISSUE TITLE
Error when opening (see image)

### ISSUE THREAD

**Issue by gustavospg** [EmissionControl2/EmissionControl2#83]
![3](https://user-images.githubusercontent.com/76918878/103487429-513dc780-4dfd-11eb-94c8-155c11058125.PNG)

**Comment by gustavospg** [comment]
I've been using it since November/December last, but today it didn't even start. I used two Reaper, Sound Particles and VCVRack before I tried to open the granulator

**Comment by jackkilgore** [comment]
This is the normal output if you run it from the terminal. Does any executable pop up?

**Comment by gustavospg** [comment]
Nothing pops up, I think.
