### ISSUE TITLE
crash in v 1.1 while trying to load new soundfile

### ISSUE THREAD

**Issue by higaru2** [EmissionControl2/EmissionControl2#94]
crash in v 1.1 while trying to load new soundfile
High Sierra.

**Comment by jackkilgore** [comment]
Ok we found this issue in #95 . So we are just packaging the release as a zip for now. Thanks for the heads up! Hopefully we will have a better solution in due time.

**Comment by higaru2** [comment]
thanks !!!!
it works !!!:))))
no problems now (so far)
thanks for speed.
fantastic granular !:)
