### ISSUE TITLE
asking for vc dependencies on win10 - not running

### ISSUE THREAD

**Issue by higaru2** [EmissionControl2/EmissionControl2#97]
v 1.1 asking for vcredist dependencies on win10 latest.
( even if all vcredist are installed )
not running.

the previous worked/works ok!
1.0.1!!!!

**Comment by jackkilgore** [comment]
#98 

Oops, accidentally had some leftover debug info that made the app dependent on Visual Studio. 

Can you try it on your machine to verify that it is working?

**Comment by higaru2** [comment]
an url to win binary?
i tried whats now in release and is the same...

**Comment by jackkilgore** [comment]
Oops just uploaded it rn. Should be available.

**Comment by higaru2** [comment]
tried!
works OK now
thank you!!!

**Comment by jackkilgore** [comment]
HURRRRAY ! Let me know if anything goes awry. Closing this issue for now. 

I guess I should mention to other people that find this thread that the latest version of Visual C++ (2019) is needed for EC2.
https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0
